library(party)
data<-subset(BreastCancer,select=-Id)
Data("BreastCancer")
library(data.table)
library(datasets)
data()
ls()
BreastCancer
library(party)
parts<-createDataPartition(data$Class,p=.8)
library(mlbench)
library(caret)
data.train<-data[parts$Resample1,]
data.test<-data[-parts$Resample1,]
m<-rpart(Class~.,data=data.train)
library(rpart)
confusionMatrix(data.test$Class,predict(m,newdata = data.test,type="class"))

parts
str(data)
str(BreastCancer)
data$Class
length(parts$Resample1)
data.up.train<-upSample(subset(data.train,select=-Class),data.train$Class)
str(data.up.train)
str(data.train)
summary(data.train$Class)
summary(data.up.train$Class)
m<-rpart(Class~.,data=data.up.train)
plot(m)
text(m)
str(data.up.train)
str(BreastCancer)
head(BreastCancer)
confusionMatrix(data.test$Class,predict(m,newdata = data.test,type="class"))
library(DMwR)
data(iris)
data<-iris[,c(1,2,5)]
data$Species<-factor(ifelse(data$Species=="setosa","rare","common"))
table(data$Species)
newdata<-SMOTE(Species~.,data,perc.over = 600,perc.under = 100)
table(newdata$Species)

library(tm)
data(crude)
summary(crude)
head(crude)
inspect(crude[1])
inspect(tm_map(tm_map(crude,tolower),removePunctuation)[1])

(x<-TermDocumentMatrix(crude))
